---
- name: Install Specific Windows Update
  hosts: all
  tasks:
    - name: Install only particular updates based on the KB numbers
      ansible.windows.win_updates:
        category_names: '*'
        accept_list:
          - KB890830
          - KB5014353
        reboot: yes
        reboot_timeout: 3600
